[package]
name = "ping-rs"
version = "0.1.0"
authors = ["Patrick José Pereira <patrickelectric@gmail.com>"]
edition = "2018"
build = "build/main.rs"

[dependencies]
bytes = "1.3.0"

[build-dependencies]
convert_case = "0.6.0"
quote = "1.0"
proc-macro2 = "1.0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.64"

[dev-dependencies]
embedded-io-adapters = {version = "0.6.1" ,features = ["std"]}
serialport = "4.3.0"
clap = { version = "3.1.6", features = ["derive"] }