[package]
name = "ping-rs"
version = "0.1.0"
authors = ["Patrick José Pereira <patrickelectric@gmail.com>"]
edition = "2018"
build = "build/main.rs"

[dependencies]
crc-any = { version = "2.3.5", default-features = false }
bytes = "1.3.0"

[build-dependencies]
convert_case = "0.6.0"
quote = "1.0"
proc-macro2 = "1.0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.64"
